//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePartage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product
    {
        //public static List<string> statusLst = new List<string>() { "draft", "to_validate", "online" };
        public static List<string> typeLst = new List<string>() { "matériel", "service" };

        public IEnumerable<SelectListItem> statusListItem { get; set; }

        public static SelectList StatusOptions { get; internal set; }

        public static List<SelectListItem> statusLst = new List<SelectListItem>
        {
            new SelectListItem { Text = "Brouillon", Value = "draft" },
            new SelectListItem { Text = "A valider", Value = "to_validate" },
            new SelectListItem { Text = "En ligne", Value = "online" },
        };


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.Leasings = new HashSet<Leasing>();
        }
    
        public int ProductID { get; set; }

        [Display(Name = "Catégorie")]
        public Nullable<int> CategoryID { get; set; }

        [Display(Name = "Membre")]
        public Nullable<int> UserID { get; set; }

        [Display(Name = "Nom")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Cout")]
        public Nullable<int> Cost { get; set; }

        [Display(Name = "Image")]
        public string Picture { get; set; }

        [Display(Name = "Type")]
        public string Type { get; set; }

        [Display(Name = "Poids (kg)")]
        public Nullable<double> Weight { get; set; }

        [Display(Name = "Etat")]
        public string Status { get; set; }

        [Display(Name = "Catégorie")]
        public virtual Category Category { get; set; }

        [Display(Name = "Membre")]
        public virtual User User { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leasing> Leasings { get; set; }
        
    }
}
